#!#!/usr/bin/bash
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso logisticregression largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso logisticregression unweighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso logisticregression 3largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso logisticregression weighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr logisticregression largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr logisticregression unweighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr logisticregression 3largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr logisticregression weighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova logisticregression largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova logisticregression unweighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova logisticregression 3largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova logisticregression weighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso randomf largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso randomf unweighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso randomf 3largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso randomf weighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr randomf largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr randomf unweighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr randomf 3largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr randomf weighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova randomf largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova randomf unweighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova randomf 3largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova randomf weighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso xgb largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso xgb unweighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso xgb 3largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py lasso xgb weighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr xgb largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr xgb unweighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr xgb 3largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py mrmr xgb weighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova xgb largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova xgb unweighted
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova xgb 3largest
python /nfs/rnas/clolivia/_Experiments/immuno_paper/laia/codes/train_radiomics.py anova xgb weighted
